### ISSUE TITLE
Show highlights before f/t pressed

### ISSUE THREAD

**Issue by james-skinner-deltatre** [joshestein/ideavim-quickscope#3]
The plugin works well but for me it doesn't save any time as you only see the highlighted letters **after** you press f or t

The vim quick-scope plugin highlights the letters on the line the cursor is on regardless of if f and t have been pressed, is it possible to do the same?

**Comment by joshestein** [comment]
Hey! Thanks for your input. I can understand how this is frustrating if you are used to automatic highlights, before any key presses.

I will need to do some digging to see how to achieve this. I think one would need to listen to all events (or at least mouse and keyboard), and from there invoke the highlight logic.

All the other ideavim emulated plugins seem to be dependent on the flow of first pressing a key, then invoking some action. I'll need to find some other plugins that are listening to all context actions, and see if I can build something similar.

**Comment by joshestein** [comment]
Good news: I figured out how to listen to caret events!

I've updated the plugin - it should now work the same as the original. That is, if `let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']` is set QS will be fired after the respective key presses. If the variable is not set, QS will always show highlights (in both directions).

I've published the plugin to the marketplace - it is now awaiting approval, which usually takes a few days.

Once approved, will you please update let me know if your issue is fixed?

**Comment by james-skinner-deltatre** [comment]
Nice one. Thank you so much! Updated and work fine so far
